openapi: 3.0.3
info:
  title: Swagger Photo Caption Contest - OpenAPI 3.0
  description: Swagger Photo Caption Contest - OpenAPI 3.0
  contact:
    name: Derek R. Cox
    url: www.thecloudguy.org
    email: derek.ryan.cox+swagger@thecloudguy.org
  license:
    name: GNU GENERAL PUBLIC LICENSE
    url: https://www.gnu.org/licenses/
  version: 1.0.0
externalDocs:
  description: GitHub Readme File
  url: https://github.com/TheCloudGuyOrg/codeAcademy_Photo_Caption_Contest/blob/main/README.md
servers:
- url: /
tags:
- name: /routes/photos
  description: Routes to Photos URLs
- name: /routes/users
  description: Routes to Users URLs
- name: /routes/captions
  description: Routes to captions URLs
paths:
  /routes/captions/:
    summary: Captions Root
    description: Root of the captions URL
    post:
      tags:
      - /routes/captions
      summary: Add Caption
      description: Add Caption
      operationId: addCaption
      responses:
        default:
          description: Default error sample response
      x-swagger-router-controller: Routescaptions
  /routes/captions/:id:
    summary: Captions by Id
    description: URL to Captions by Id
    get:
      tags:
      - /routes/captions
      summary: Get Caption by Id
      description: Get Caption by Id
      operationId: getCaptionById
      responses:
        default:
          description: Default error sample response
      x-swagger-router-controller: Routescaptions
    put:
      tags:
      - /routes/captions
      summary: Update Caption
      description: Update Caption
      operationId: updateCaption
      responses:
        default:
          description: Default error sample response
      x-swagger-router-controller: Routescaptions
  /routes/photos/:
    summary: Photos Root
    description: Photos Root
    get:
      tags:
      - /routes/photos
      summary: Get List of Photos
      description: Get a List of Photos
      operationId: getPhotos
      responses:
        default:
          description: Default error sample response
      x-swagger-router-controller: Routesphotos
    post:
      tags:
      - /routes/photos
      summary: Add Photo
      description: Add Photo
      operationId: addPhotos
      responses:
        default:
          description: Default error sample response
      x-swagger-router-controller: Routesphotos
  /routes/photos/:id:
    summary: Photos by ID
    description: URL to Photos by Id
    get:
      tags:
      - /routes/photos
      summary: Get Photos by Id
      description: Get Photos by Id
      operationId: getPhotosById
      responses:
        default:
          description: Default error sample response
      x-swagger-router-controller: Routesphotos
    put:
      tags:
      - /routes/photos
      summary: Update Photo
      description: Update Photo
      operationId: updatePhotos
      responses:
        default:
          description: Default error sample response
      x-swagger-router-controller: Routesphotos
    delete:
      tags:
      - /routes/photos
      summary: Delete Photo
      description: Delete Photo
      operationId: deletePhotos
      responses:
        default:
          description: Default error sample response
      x-swagger-router-controller: Routesphotos
  /routes/users/:
    summary: Users Root
    description: Root of the users URL
    get:
      tags:
      - /routes/users
      summary: Get List of Users
      description: Get List of Users
      operationId: getUsers
      responses:
        default:
          description: Default error sample response
      x-swagger-router-controller: Routesusers
    post:
      tags:
      - /routes/users
      summary: Add User
      description: Add User
      operationId: addUser
      responses:
        default:
          description: Default error sample response
      x-swagger-router-controller: Routesusers
  /routes/users/:id:
    summary: Users by Id
    description: URL to Users by Id
    get:
      tags:
      - /routes/users
      summary: Get Users by Id
      description: Get Users by Id
      operationId: getUsersById
      responses:
        default:
          description: Default error sample response
      x-swagger-router-controller: Routesusers
    put:
      tags:
      - /routes/users
      summary: Update Users
      description: Update Users
      operationId: updateUsers
      responses:
        default:
          description: Default error sample response
      x-swagger-router-controller: Routesusers
  /routes/users/login:
    summary: User Logins
    description: URL to Logins
    post:
      tags:
      - /routes/users
      summary: Add Login
      description: Add Login
      operationId: addLogin
      responses:
        default:
          description: Default error sample response
      x-swagger-router-controller: Routesusers
components: {}
